title: nytewuff
description: "A personal website for nytewuff."
permalink: /post/:year/:month/:day/:title
url: "https://nytewuff.com"

include:
  - .nojekyll

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-file-size
  - jekyll-node-module
  - jekyll-redirect-from

node_modules:
  modules_dir: node_modules
  copy:
  - source: .
    target: node_modules

sass:
  load_paths:
    - _sass
    - node_modules
