title: nytewuff
description: "A personal website for nytewuff."
permalink: /post/:year/:month/:day/:title
baseurl: ""
url: "https://nytewuff.com"
twitter_username: nytewuff

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-file-size
  - jekyll-redirect-from

sass:
  load_paths:
    - _sass
    - node_modules
include: 
  - .nojekyll
  - _icons
  - node_modules
