name: Jekyll
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install bundler

      - run: bundle install

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.TOKEN }}
